<?php 
use Magento\Customer\Block\Widget\Name;
use Magento\Customer\Helper\Address as AddressH;
use Verdepieno\Core\CustomerAddressForm as F;
use Verdepieno\Core\Setup\UpgradeData as D;
/** @var $block \Magento\Customer\Block\Form\Register */
echo $block->getChildHtml('form_fields_before');
echo $block->getChildHtml('customer.form.register.extra');
?>
<form
	action="<?= $block->getPostActionUrl() ?>"
	autocomplete="off"
	class="form create account form-create-account"
	enctype="multipart/form-data"
	id="form-validate"
	method="post"
>
    <fieldset class="fieldset create info">
        <input type="hidden" name="success_url" value="<?= $block->getSuccessUrl() ?>" />
        <input type="hidden" name="error_url" value="<?= $block->getErrorUrl() ?>" />
        <?= $block->getLayout()->createBlock(Name::class)
			->setObject($block->getFormData())
			->setForceUseCustomerAttributes(true)
			->toHtml() 
		?>
        <?php if ($block->isNewsletterEnabled()): ?>
            <div class="field choice newsletter">
                <input
					<?php if ($block->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?>
					class="checkbox"
					id="is_subscribed"
					name="is_subscribed"
					title="<?= __('Sign Up for Newsletter') ?>"
					type="checkbox"
					value="1"
				/>
                <label for="is_subscribed" class="label"
				><span><?= __('Sign Up for Newsletter') ?></span></label>
            </div>
            <?= $block->getChildHtml('customer.form.register.newsletter')?>
        <?php endif ?>

        <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
        <?php if ($_dob->isEnabled()): ?>
            <?= $_dob->setDate($block->getFormData()->getDob())->toHtml() ?>
        <?php endif ?>        

        <?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
        <?php if ($_gender->isEnabled()): ?>
            <?= $_gender->setGender($block->getFormData()->getGender())->toHtml() ?>
        <?php endif ?>
    </fieldset>
	<?php $this->setShowAddressFields(true); ?>
    <?php if ($block->getShowAddressFields()): ?>
        <fieldset class="fieldset address">
            <input type="hidden" name="create_address" value="1" />           
            <div class="field telephone">
                <label for="telephone" class="label"><span><?= __('Phone Number') ?></span></label>
                <div class="control">
                    <input
						class="input-text <?= $this->helper(AddressH::class)->getAttributeValidationClass('telephone') ?>"
						id="telephone"
						name="telephone"
						title="<?= __('Phone Number') ?>"
						type="text"
						value="<?= $block->escapeHtml($block->getFormData()->getTelephone()) ?>"
					/>
                </div>
            </div>

            <?php $_streetValidationClass = $this->helper(AddressH::class)->getAttributeValidationClass('street'); ?>

            <div class="field street required">
                <label for="street_1" class="label"><span><?= __('Street Address') ?></span></label>
                <div class="control">
                    <input
						class="input-text <?= $_streetValidationClass ?>"
						id="street_1"
						name="street[]"
						title="<?= __('Street Address') ?>"
						type="text"
						value="<?= $block->escapeHtml($block->getFormData()->getStreet(0)) ?>"
					/>
                    <div class="nested">
                        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                        <?php for ($_i = 2, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                            <div class="field additional">
                                <label class="label" for="street_<?= $_i ?>">
                                    <span><?= __('Address') ?></span>
                                </label>
                                <div class="control">
                                    <input type="text" name="street[]" value="<?= $block->escapeHtml($block->getFormData()->getStreetLine($_i - 1)) ?>" title="<?= __('Street Address %1', $_i) ?>" id="street_<?= $_i ?>" class="input-text <?= $_streetValidationClass ?>">
                                </div>
                            </div>
                        <?php endfor; ?>
                    </div>
                </div>
            </div>

            <div class="field required">
                <label for="city" class="label"><span><?= __('City') ?></span></label>
                <div class="control">
                    <input type="text" name="city" value="<?= $block->escapeHtml($block->getFormData()->getCity()) ?>" title="<?= __('City') ?>" class="input-text <?= $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city') ?>" id="city">
                </div>
            </div>

            <div class="field region required">
                <label for="region_id" class="label"><span><?= __('State/Province') ?></span></label>
                <div class="control">
                    <select id="region_id" name="region_id" title="<?= __('State/Province') ?>" class="validate-select" style="display:none;">
                        <option value=""><?= __('Please select a region, state or province.') ?></option>
                    </select>
                    <input type="text" id="region" name="region" value="<?= $block->escapeHtml($block->getRegion()) ?>" title="<?= __('State/Province') ?>" class="input-text <?= $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>" style="display:none;">
                </div>
            </div>
			
            <div class="field zip required">
                <label for="zip" class="label"><span><?= __('Zip/Postal Code') ?></span></label>
                <div class="control">
                    <input type="text" name="postcode" value="<?= $block->escapeHtml($block->getFormData()->getPostcode()) ?>" title="<?= __('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?= $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode') ?>">
                </div>
            </div>
			
            <div class="field country required" style='display:none;'>
                <label for="country" class="label"><span><?= __('Country') ?></span></label>
                <div class="control">
                    <?= $block->getCountryHtmlSelect() ?>
                </div>
            </div>
            <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes');?>
            <?php if ($addressAttributes): ?>
                <?php $addressAttributes->setEntityType('customer_address'); ?>
                <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]');?>
                <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address');?>
                <?= $addressAttributes->setShowContainer(false)->toHtml()?>
            <?php endif;?>

            <input type="hidden" name="default_billing" value="1">
            <input type="hidden" name="default_shipping" value="1">
			
			<div class='field need_invoice'>
				<div class="label">
					<input type='checkbox' id="need_invoice"
					/><label for='need_invoice'><?= __('Serve fattura?') ?></label>
				</div>
			</div>
			<div class="field company">
                <label
					for="company"
					class="label"
				><span><?= __('Company') ?></span><span style='color:#e02b27'>*</span></label>
                <div class="control">
                    <input
						class="input-text <?= $this->helper(AddressH::class)->getAttributeValidationClass('company') ?>"
						id="company"
						name="company"
						title="<?= __('Company') ?>"
						type="text"
						value="<?= $block->escapeHtml($block->getFormData()->getCompany()) ?>"
					/>
                </div>
            </div>
			<?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
			<?php if ($_taxvat->isEnabled()): ?>
				<?= str_replace("</span></label>",'</span><span style="color:red">*</span></label>',$_taxvat->setTaxvat($block->getFormData()->getTaxvat())->toHtml()); ?>
			<?php endif ?>

			<?php
				echo F::f(D::F__CODICE_SDI, D::T__CODICE_SDI);
				echo F::f(D::F__PEC, D::T__PEC);
			?>

			<div class='field ind_company'>
				<div class="label">
					<input type='checkbox' id="ind_company" /> <label for='ind_company'><?= __('Azienda individuale') ?></label>
				</div>
			</div>

			<div class="field fiscal_code">
				<label class="label" for="fiscal_code"><span><?= __('Codice fiscale') ?></span><span style='color:#e02b27'>*</span></label>
				<div class="control">
					<input type="text" id="fiscal_code" name="privatecompany_fiscalcode" value="" title="Codice fiscale" class="input-text "  >
				</div>
			</div>
			<div class="field addressdeault">
				<div class="label">
					<input type="checkbox" name="addressdeault" id="addressdeault" /> <label for="addressdeault"><?= __('Aggiungi un indirizzo di spedizione diverso') ?></label>
				</div>
			</div>			
			
        </fieldset>

    <?php endif; ?>
    
    <fieldset class="fieldset fieldaddressdeault" style="display:none">
		<div class="field addfirstname required">
			<label class="label" for="addfirstname"><span><?= __('First Name') ?></span></label>
			<div class="control">
				<input name="addfirstname" id="addfirstname" title="<?= __('First Name') ?>" class="input-text required" type="text" />
			</div>
		</div>
		<div class="field addlastname required">
			<label class="label" for="addlastname"><span><?= __('Last Name') ?></span></label>
			<div class="control">
				<input name="addlastname" id="addlastname" title="<?= __('Last Name') ?>" class="input-text required" type="text" />
			</div>
		</div>
		<div class="field addtelenum required">
			<label class="label" for="addtelenum"><span><?= __('Telephone number') ?></span></label>
			<div class="control">
				<input name="addtelenum" id="addtelenum" title="<?= __('Telephone number') ?>" class="input-text required" type="text" />
			</div>
		</div>
		<div class="field addaddress required">
			<label class="label" for="addaddress"><span><?= __('Address') ?></span></label>
			<div class="control">
				<input name="addaddress[]" id="addaddress" title="<?= __('Address') ?>" class="input-text required" type="text" />
			</div>
		</div>
		<div class="field addaddress2">
			<label class="label" for="addaddress"><span></span></label>
			<div class="control field">
				<input type="text" name="addaddress[]" title="<?= __('Address') ?>" class="input-text">
			</div>
		</div>
		<div class="field required addcity">
			<label for="addcity" class="label"><span><?php  echo __('City') ?></span></label>
			<div class="control">
				<input type="text" name="addcity" title="<?= __('City') ?>" class="input-text <?= $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city') ?>" id="addcity">
			</div>
		</div>
	   <div class="field addregion required">
			<label for="addregion_id" class="label"><span><?php  echo __('State/Province') ?></span></label>
			<div class="control">
				<select id="addregion_id" name="addregion_id" title="<?= __('State/Province') ?>" class="validate-select" style="display:none;">
					<option value=""><?php  echo __('Please select a region, state or province.') ?></option>
				</select>
				<input type="text" id="region" name="addregion" value="<?= $block->escapeHtml($block->getRegion()) ?>" title="<?php  echo __('State/Province') ?>" class="input-text <?php  echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>" style="display:none;">
			</div>
		</div>
		<div class="field addcountry required" style="display: none;">
			<label for="addcountry" class="label"><span><?= __('Country') ?></span></label>
			<div class="control">
				<?= $block->getCountryHtmlSelect() ?>
			</div>
		</div>
		<div class="field addzip required">
			<label for="addzip" class="label"><span><?= __('Zip/Postal Code') ?></span></label>
			<div class="control">
				<input type="text" name="addzip" value="<?= $block->escapeHtml($block->getFormData()->getPostcode()) ?>" title="<?= __('Zip/Postal Code') ?>" id="addzip" class="input-text validate-zip-international <?= $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode') ?>">
			</div>
		</div>
	</fieldset>
	 <!-- end start second add -->	
    <fieldset class="fieldset create account" data-hasrequired="<?= __('* Required Fields') ?>">
        <legend class="legend"><span><?= __('Sign-in Information') ?></span></legend><br>
        <div class="field required">
            <label for="email_address" class="label"><span><?= __('Email') ?></span></label>
            <div class="control">
                <input type="email" name="email" autocomplete="email" id="email_address" value="<?= $block->escapeHtml($block->getFormData()->getEmail()) ?>" title="<?= __('Email') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <div class="field password required" data-mage-init='{"passwordStrengthIndicator": {}}'>
            <label for="password" class="label"><span><?= __('Password') ?></span></label>
            <div class="control">
                <input type="password" name="password" id="password"
                       title="<?= __('Password') ?>"
                       class="input-text"
                       data-password-min-length="<?= $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                       data-password-min-character-sets="<?= $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>"
                       data-validate="{required:true, 'validate-customer-password':true}"
                       autocomplete="off">
                <div id="password-strength-meter-container" data-role="password-strength-meter" >
                    <div id="password-strength-meter" class="password-strength-meter">
                        <?= __('Password Strength'); ?>:
                        <span id="password-strength-meter-label" data-role="password-strength-meter-label" >
                            <?= __('No Password'); ?>
                        </span>
                    </div>
                </div>
            </div>

        </div>
        <div class="field confirmation required">
            <label for="password-confirmation" class="label"><span><?= __('Confirm Password') ?></span></label>
            <div class="control">
                <input type="password" name="password_confirmation" title="<?= __('Confirm Password') ?>" id="password-confirmation" class="input-text" data-validate="{required:true, equalTo:'#password'}" autocomplete="off">
            </div>
        </div>
		<?php
			// 2019-03-06 Dmitry Fedyuk https://www.upwork.com/fl/mage2pro
			// The automatical block rendering has stopped working for an unknown reason:
			// 		echo $block->getChildHtml('form_additional_info');
			$b = df_block(\MSP\ReCaptcha\Block\Frontend\ReCaptcha::class, [
				'jsLayout' => ['components' => ['msp-recaptcha' => [
					'component' => 'MSP_ReCaptcha/js/reCaptcha'
					,'zone' => 'create'
				]]]
				,'name' => 'msp-recaptcha'
			], 'MSP_ReCaptcha::msp_recaptcha.phtml');
			echo $b->toHtml();
		?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" title="<?= __('Create an Account') ?>"><span><?= __('Create an Account') ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>"><span><?= __('Back') ?></span></a>
        </div>
    </div>
</form>
<script>
require([
    'jquery',
    'mage/mage'
], function($){

    var dataForm = $('#form-validate');
    var ignore = <?= $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null'; ?>;
    
    dataForm.mage('validation', {
    <?php if ($_dob->isEnabled()): ?>
        errorPlacement: function(error, element) {
            if (element.prop('id').search('full') !== -1) {
                var dobElement = $(element).parents('.customer-dob'),
                    errorClass = error.prop('class');
                error.insertAfter(element.parent());
                dobElement.find('.validate-custom').addClass(errorClass)
                    .after('<div class="' + errorClass + '"></div>');
            }
            else {
                error.insertAfter(element);
            }
        },
        ignore: ':hidden:not(' + ignore + ')'
    <?php else: ?>
        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
    <?php endif ?>
    }).find('input:text').attr('autocomplete', 'off');
	
	$('#need_invoice').on('click', function() {
		if ($('#need_invoice').is(':checked')){
			$('.taxvat').show();
			$('.company').show();
			$('.ind_company').show();
			$('.<?= D::F__CODICE_SDI ?>').show();
			$('.<?= D::F__PEC ?>').show();
			$('.ind_company').show();
			$('#taxvat').addClass('required-entry');
			$("#taxvat").attr("aria-required","true");
			$('#company').addClass('required-entry');
			$("#company").attr("aria-required","true");
		}
		else {
			$('.taxvat').hide();
			$('.company').hide();
			$('.ind_company').hide();
			$('.<?= D::F__CODICE_SDI ?>').hide();
			$('.<?= D::F__PEC ?>').hide();
			$('#taxvat').removeClass('required-entry');
			$('#taxvat').removeClass('mage-error');
			$("#taxvat").removeAttr("aria-required");
			$("#taxvat").removeAttr("aria-invalid");
			$("#taxvat").removeAttr("aria-describedby");
			if ($('#taxvat-error').length) {
				$('#taxvat-error').remove();
			}
			$('#company').removeClass('required-entry');
			$('#company').removeClass('mage-error');
			$("#company").removeAttr("aria-required");
			$("#company").removeAttr("aria-invalid");
			$("#company").removeAttr("aria-describedby");
			if ($('#company-error').length) {
				$('#company-error').remove();
			}
			$('.fiscal_code').hide();
			$('#fiscal_code').removeClass('required-entry');
			$('#fiscal_code').removeClass('mage-error');
			$("#fiscal_code").removeAttr("aria-required");
			$("#fiscal_code").removeAttr("aria-invalid");
			$("#fiscal_code").removeAttr("aria-describedby");
			if ($('#fiscal_code-error').length) {
				$('#fiscal_code-error').remove();
			}
		}
	});
	
	$('#ind_company').on('click', function() {
		if($('#ind_company').is(':checked')){
			$('.fiscal_code').show();			
			$('#fiscal_code').addClass('required-entry');
			$("#fiscal_code").attr("aria-required","true");
		}else{
			$('.fiscal_code').hide();
			$('#fiscal_code').removeClass('required-entry');
			$('#fiscal_code').removeClass('mage-error');
			$("#fiscal_code").removeAttr("aria-required");
			$("#fiscal_code").removeAttr("aria-invalid");
			$("#fiscal_code").removeAttr("aria-describedby");
			if ($('#fiscal_code-error').length) {
				$('#fiscal_code-error').remove();
			}
		}
	});
	$('#addressdeault').on('click', function() {
		if($('#addressdeault').is(':checked')){
			$('.fieldaddressdeault').show();
		}else{
			$('.fieldaddressdeault').hide();
		}
	});
	$('.addcountry select').attr("id","addcountry");
});
</script>
<?php if ($block->getShowAddressFields()): ?>
<script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?=($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "<?= $block->getFormData()->getRegionId() ?>",
                "countriesWithOptionalZip": <?= $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        }	
    }
</script>
<script type="text/x-magento-init">
    {
        "#addcountry": {
            "regionUpdater": {
                "optionalRegionAllowed": <?=($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#addregion_id",
                "regionInputId": "#addregion",
                "postcodeId": "#addzip",
                "form": "#form-validate",
                "regionJson": <?= $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "<?= $block->getFormData()->getRegionId() ?>",
                "countriesWithOptionalZip": <?= $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        }	
    }
</script>
<style type='text/css'>
	.need_invoice .label{width:31.7% !important;}
	.field.taxvat {display:none;}
	.field.company {display:none;}
	.field.country {display:none !important;}
	.field.<?= D::F__CODICE_SDI ?> {display:none;}
	.field.<?= D::F__PEC ?> {display:none;}
	.ind_company {display:none;}
	.ind_company .label {width:35% !important;}
	.field.fiscal_code {display:none;}
	.addcountry {display:none !important;}
</style>
<?php endif; ?>
